# -*- coding: utf-8 -*-
"""ttt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PJbvFmnKdvi2s3pN0CHNq0Tmas9iWv5d
"""

!pip uninstall openai -y
!pip install openai==0.28.0

import openai

# 定義過濾關鍵字列表
filtered_keywords = ["填寫日記", "填寫星期一日記", "填寫星期二日記",'填寫星期三日記',"填寫星期四日記", "填寫星期五日記",'填寫星期六日記','填寫星期日日記','功能選單','查看專屬情緒曲線']

# 定義用來檢查訊息是否包含關鍵字的函數
def contains_filtered_keyword(message):
    for keyword in filtered_keywords:
        if keyword in message:
            return True
    return False

# 輸入你的 OpenAI API 金鑰
openai.api_key = "自己的api key"

# 定義聊天機器人回覆邏輯
def chatbot_response(user_message):
    if contains_filtered_keyword(user_message):
        # 不傳送訊息到 OpenAI，也不返回任何回覆
        return None
    else:
        response = openai.Completion.create(
            engine="gpt-3.5-turbo-instruct",  # 使用新的模型
            prompt=user_message,
            max_tokens=150
        )
        return response.choices[0].text.strip()

# 示範使用
user_message = "填寫日記"
response = chatbot_response(user_message)
print(response)